language: generic
sudo: required
services:
    - docker
before_install:
    - CD simple
    - docker build -t vikramcse/docker-react -f Dockerfile.dev .
script:
    - CD simple
    - docker run -e CI=true vikramcse/docker-react npm run test -- --coverage
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-720691588208"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
